version: '3.4'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile.Client
    ports:
      - "44554:80"
      - "44555:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=5a1e064c-ac87-4bd2-9301-e48c3f4ea9e9
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/WebAPI.pfx
    volumes:
      - ./Cert:/root/.aspnet/https:ro
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.WebAPI
    ports:
      - "44666:44377"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44377
      - ASPNETCORE_Kestrel__Certificates__Default__Password=5a1e064c-ac87-4bd2-9301-e48c3f4ea9e9
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/WebAPI.pfx
    volumes:
      - ./Cert:/root/.aspnet/https:ro
